name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up g++
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build all C++ files
        id: build
        continue-on-error: true
        run: |
          # Create an array of available .cpp files
          cpp_files=(${GITHUB_WORKSPACE}/*.cpp)
          
          # Compile all .cpp files
          for cpp_file in *.cpp; do
            g++ -c "$cpp_file" -o "${cpp_file%.cpp}.o" || exit 1
          done
          
          # Link the object files into an output executable
          g++ *.o -o halio.out
          
          # List available files in the workspace
          ls -l
 
      - name: Summary
        run: |
          if [ "${{ steps.build.outcome }}" == "success" ]; then
            echo "::notice::✅ Build process succeeded."
          else
            echo "::error::❌ Build process failed."
            echo "::error::Check workflow execution steps."
          fi
