name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up g++
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build all C++ files
        run: |
          # Create an array of available .cpp files
          cpp_files=(${GITHUB_WORKSPACE}/*.cpp)
          
          # Compile all .cpp file
          for cpp_file in "${cpp_files[@]}"; do
            g++ -c "$cpp_file" -o "${cpp_file%.cpp}.o"
          done
          
          # Link the object files into an output executable
          g++ ${cpp_files[@]/%/.o} -o "${GITHUB_WORKSPACE}/halio.out"
          
          # List available files in the workspace
          ls -l "${GITHUB_WORKSPACE}"
